# Generated by Django 3.0.7 on 2020-06-25 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutritional_info',
        ),
        migrations.CreateModel(
            name='NutritionalInfoValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(blank=True, max_length=120, null=True)),
                ('nutritional_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.NutritionalInfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional_info',
            field=models.ManyToManyField(through='restaurant.NutritionalInfoValues', to='restaurant.NutritionalInfo'),
        ),
    ]
